source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'FLTutorial_Example', :exclusive => true do
  pod 'FLTutorial', :path => '../'
end

target 'FLTutorial_Tests', :exclusive => true do
  pod 'FLTutorial', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
